### ISSUE TITLE
egui UI is blurry, mouse input is offset

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#1014]
As the title says, the egui UI on the left is very blurry. The mouse cursor isn't registered where it actually is. See this screenshot:
![Screenshot from 2022-08-30 10-25-18](https://user-images.githubusercontent.com/85732/187389565-390a869d-b17e-4dce-8a4c-027c3d457b5a.png)

The blurriness is a bit subtle on this screenshot (although it's very clear in the original, especially if you've seen the difference). But you can clearly see that the mouse cursor is hovering over "Render original UI", but "Show egui settings UI" is activated.

I'm observing the problem on my Linux/Gnome setup (AMD GPU, although not sure that makes a difference). I'm pretty sure this came in with the recent egui/wgpu/winit upgrade (https://github.com/hannobraun/Fornjot/pull/975). The problem seems to be related to the scale factor of my HiDPI display. If I change the scale factor to 100% in the gnome settings, it works as expected.

I suspect that something has changed in regards to HiDPI handling in either winit or egui. Maybe the solution will become obvious when going over the changelogs.

**Comment by devanlooches** [comment]
Just as extra information, I am getting the same result on my Mac.

**Comment by hannobraun** [comment]
Thanks for the info, @devanlooches! I think this increases the likelihood of this being a HiDPI display issue. Good to know it's not some platform-specific problem. That would be annoying.

**Comment by hannobraun** [comment]
I've looked into this, but no luck. I couldn't find anything that looked suspicious or was obviously missing.

**Comment by hannobraun** [comment]
I just discovered that this happens to me with X.org, but not with Wayland.

**Comment by hannobraun** [comment]
Fixed in #1266.

Thanks again, @erenoku!
