### ISSUE TITLE
Loading model libraries doesn't work on platforms other than Linux

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/fornjot#11]
Right now, the host application expects the dynamic library to end with `.so`, which is correct on Linux. It should either fall back to other file endings to support more platforms, or there might be a way to override the file name outright, and set it to something like `.model`.

**Comment by hannobraun** [comment]
In case anyone wants to take a look, the library is loaded in [`model.rs`](https://github.com/hannobraun/fornjot/blob/06d90d846c38249466409a73e3a398f3d46de49f/src/model.rs#L43). If it's practical to override the whole file name, this [also needs to happen in `model.rs`](https://github.com/hannobraun/fornjot/blob/06d90d846c38249466409a73e3a398f3d46de49f/src/model.rs#L30-L33)

**Comment by hannobraun** [comment]
I initially thought of this as an enhancement (as in, it works fine, it should work fine in more places), but I think it makes more sense to classify it as a bug.

**Comment by Bandsberg** [comment]
For OSX: dynamic library: .dylib (e.g. libspacer.dylib) results in "Error: Error request adapter". Error defined in renderer.rs
Will continue to investigate next time I have time

**Comment by hannobraun** [comment]
@Bandsberg I think what you're seeing is most likely #10, not this issue.

**Comment by hannobraun** [comment]
Fixed by @Bandsberg in #23.
