### ISSUE TITLE
Fix CD warning

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#1270]
The continuous deployment build currently emits two warnings: https://github.com/hannobraun/Fornjot/actions/runs/3319079604

I believe the one about macOS is not relevant for us, but this one is:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

According to the linked blog post, **this will stop working 2023-05-31**.

I believe this piece of code is responsible for the warning:
https://github.com/hannobraun/Fornjot/blob/63a7518c29956c9be2bd49b36c868b41f73b2150/tools/release-operator/src/github.rs#L71-L75

Labeling https://github.com/hannobraun/Fornjot/labels/good%20first%20issue, as this issue doesn't require any knowledge about Fornjot to address.

**Comment by kopackiw** [comment]
Happy to work on that later today!
