### ISSUE TITLE
Model version check is disabled on Windows

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#1307]
When loading a model, the Fornjot app checks the Fornjot version that this model model uses, to prevent mystery errors due to incompatibilities. This check is currently disabled on Windows. There's a bug that prevents it from working there. See #1303 for context.

It would be great if we fixed that bug, and enabled the same version check on all platforms. Unfortunately, I don't have access to a Windows machine and lack Windows expertise. Labeling as https://github.com/hannobraun/Fornjot/labels/help%20wanted, as help would be especially appreciated!

**Comment by hannobraun** [comment]
I went over the version comparison code with a fine comb and found (and fixed!) a potential soundness hole. I don't know if that was actually the problem reported in #1303, but if it was, it's possible that the version check can be enabled on Windows without further changes.

**Comment by MartinKavik** [comment]
I've just pulled the latest `main` and deleted the condition for Windows and tried `println!` the versions and everything seems to work as expected now on Windows 10. Good job!  

Btw is it possible to somehow filter `debug!` messages for a specific crate or a project? When I set `RUST_LOG=DEBUG` I see only a sea of `wgpu_*` and `fj_viewer*` messages.

**Comment by hannobraun** [comment]
> I've just pulled the latest `main` and deleted the condition for Windows and tried `println!` the versions and everything seems to work as expected now on Windows 10. Good job!

Thank you! Such a subtle thing. I wasn't very optimistic that this would actually solve it!


> Btw is it possible to somehow filter `debug!` messages for a specific crate or a project? When I set `RUST_LOG=DEBUG` I see only a sea of `wgpu_*` and `fj_viewer*` messages.

Yes: `RUST_LOG=fj_host=debug cargo run`

I think you can go even more fine-grained, by specifying this on the module level. And you can probably chain multiple directives using `,`, but I might not remember the syntax correctly.
