### ISSUE TITLE
Adding dimension rendering?

### ISSUE THREAD

**Issue by therealprof** [hannobraun/Fornjot#134]
I was having a quick look at how difficult it would be to add an overlay to display the dimensions of the rendered object but I got lost in the tons of indirections to figure out where the actually rendered data would have to be created.

**Comment by hannobraun** [comment]
Thanks for opening this issue, @therealprof!

I think displaying the model dimensions makes sense. We already [compute an axis-aligned bounding box](https://github.com/hannobraun/Fornjot/blob/621ff19716503ac62b5c10c7a875c94a6fa74a5b/src/main.rs#L66), and that information could be displayed on screen.

Currently the only place where that kind of thing is done is for the config UI (the three lines of text at the top of the screen). See [`graphics/config_ui.rs`](https://github.com/hannobraun/Fornjot/blob/main/src/graphics/config_ui.rs). If you want to add more UI elements, the best place to start is to extend/adapt this code.

Please note that the current UI code is temporary, and I'd like to replace it with something more versatile (see #116). I don't intend to work on any UI stuff until that happens, personally. But I don't see any harm in extending what's currently there a bit more, if you're interested in working on that.
