### ISSUE TITLE
Star model displays triangulation issues

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#143]
When changing the number of pointy ends of the star model, some values display triangulation issues.

Here's the 12-pointed star:
![Screenshot from 2022-02-07 17-24-55](https://user-images.githubusercontent.com/85732/152829771-06547278-0be0-4776-9878-cd033a19ed7e.png)

And here's the 15-pointed star:
![Screenshot from 2022-02-07 17-25-41](https://user-images.githubusercontent.com/85732/152829884-61793931-63bc-4eb0-ac1b-31556247f276.png)

These might or might not be the result of issues that are already documented in #105, but in any case, I think it would be a mistake to fix more triangulation bugs without adding test cases to guard against regressions. Labeling this issue as blocked by #105.

**Comment by hannobraun** [comment]
#138 has been addressed, but the problems described here are still present. This means this only blocked on #105 now. Updated the issue description accordingly.

**Comment by hannobraun** [comment]
@therealprof has reported some weird data in #246. See also my comment there.

I'm going to repeat some of what I said there here, as it directly relates to this issue.

---

The screenshots here show whole triangles that shouldn't be there. This is most likely a problem in the [triangulation code](https://github.com/hannobraun/Fornjot/blob/a774cc94fb063d062074fee68a8e3a1f4c1c078e/src/kernel/topology/faces.rs#L98-L234) or the [approximation code](https://github.com/hannobraun/Fornjot/blob/a774cc94fb063d062074fee68a8e3a1f4c1c078e/src/kernel/approximation.rs) that feeds it data. More specifically, I suspect that it might be a problem with the point-in-polygon testing that's necessary as part of the triangulation ([[1]](https://github.com/hannobraun/Fornjot/blob/a774cc94fb063d062074fee68a8e3a1f4c1c078e/src/kernel/topology/faces.rs#L151-L158) and [[2]](https://github.com/hannobraun/Fornjot/blob/a774cc94fb063d062074fee68a8e3a1f4c1c078e/src/kernel/topology/faces.rs#L185-L212)), which has known issues (#105).

A word of warning: That triangulation code is pretty gnarly, and overdue for a cleanup. See #105.

**Comment by therealprof** [comment]
I've trimmed down the example a bit to only render the "outer" sketch so there're less datapoints (and involved code) to look at...

Problems start at 12 "points", here's what that looks like:

<img width="822" alt="Screenshot 2022-02-24 at 11 39 14" src="https://user-images.githubusercontent.com/3321888/155508725-e4228205-874f-4e5a-9323-d74e459fb60b.png">

**Comment by hannobraun** [comment]
Looks like triangles that should be kept are being removed instead, which again points to issues with the point-in-polygon test.

**Comment by hannobraun** [comment]
Even the default version of the star model is broken now:
![Screenshot from 2022-04-09 09-17-33](https://user-images.githubusercontent.com/85732/162561348-c0b8865c-ecee-4e58-bb29-2d8bdd07fe7c.png)

Most likely, this happened yesterday in #439.

I'm looking into it. #439 was intended to be a pure refactoring without any functional changes.

**Comment by hannobraun** [comment]
I think I get it. The problem was introduced in this commit: https://github.com/hannobraun/Fornjot/pull/439/commits/eb187e033ea696b9b4d08060ff800f92748693d9

This changes the calculation of the point the ray shoots to. The algorithm itself stays the same, just the ray that is used for determining if a triangle is part of the shape is changed, meaning it could hit different edges in different places, at different angles.

There are known problem with that code. I'm very sure that this commit didn't introduce any new issues, it just shuffled things around, so that the default 5-pointed star model now triggers those bugs. This is unfortunate, but some fallout is to be expected, as I work on the triangulation code.

I don't intend to do anything about this specific instance of the bug, but I'm actively working on fixing this and other triangulation bugs, so I hope this will improve soon.
