### ISSUE TITLE
Print stack trace for panics that originate in model code

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#1569]
Executing a `todo!()` in the code of a model results in this error message:
![Screenshot from 2023-02-07 13-00-09](https://user-images.githubusercontent.com/85732/217239505-363800e8-0f31-4df1-a750-a7581e8df2e5.png)

This is not ideal, as it lacks some critical information:

- It doesn't explain *that* a panic occurred.
- It doesn't show *where* that panic occurred.

Ideally, the error message should clearly explain that there was a panic while loading the model, originating from the model code, and print a stack trace for the panic. Even more ideally, this stack trace would leave out any irrelevant parts from outside of the model code, and only show the stack trace of the panic starting from the model function.

Panic handling for models centers around the [`on_panic`](https://github.com/hannobraun/Fornjot/blob/ed08c4c8d99d3e146a9a815406e02e276a040d77/crates/fj/src/abi/mod.rs#L121-L132) function, and I think that any necessary changes will either be completely contained within that function, or at least center around it (if changing the function's signature is necessary, that will require changes in the code using that function).

Labeling as https://github.com/hannobraun/Fornjot/labels/good%20first%20issue, as this is a fairly localized change. It will require some knowledge of Rust panic and error handling to address, but shouldn't require much knowledge about Fornjot in particular.

**Comment by IamTheCarl** [comment]
Looking into the issue with the panic handler not intercepting panics caught by `catch_unwind`, it seems that the panic hook is a global variable and that each module we're loading has defined its own personal panic hook, so that's why that isn't working. We'd have to make some kind of change to the client library to fix that, or use a completely different approach to models.

**Comment by IamTheCarl** [comment]
In case you're curious, [here's my branch](https://github.com/IamTheCarl/Fornjot/tree/better-model-panics) implementing what I have. Most of the changes are [here](https://github.com/IamTheCarl/Fornjot/blob/better-model-panics/crates/fj/src/abi/mod.rs#L158).

**Comment by hannobraun** [comment]
Thank you for looking into this, @IamTheCarl!

> I've started to take a crack at implementing this and have run into problems.
> `catch_unwind` will not give you the information you are looking for, period.
> I'm not sure why. I think they just don't want you doing that.

That's too bad.

Maybe the issue is that the backtrace isn't captured? You have to run a Rust application with `RUST_BACKTRACE=1` to get one for panic messages, after all. If that's the case, I wonder if we can enable that unconditionally for model code somehow?


> To top it off, [official documentation](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) suggests catching panics is a bad practice.

It is bad practice to use it as a replacement for `Result`. But I think it's appropriate for a case like this, where you have foreign code that you don't control, and you have a clear boundary where you want panics not to propagate any more.

On top of that, it's also *necessary* in this case. There's an FFI boundary between the Fornjot application and models (even though it's Rust on both sides), and panicking over an FFI boundary is undefined behavior. That must be avoided.


> It looks to me like the [client library](https://crates.io/crates/fj) is designed to be serialized. Maybe instead of compiling to a lib and linking that in at runtime, we should build an executable and print that data to stdout?

That's an interesting idea!

However, I'm not sure how well that concept will hold up in the future. Please note that the plan is to migrate from the current system to WASM (#71), and also to be able to run in browsers.


> We'd have to make some kind of change to the client library to fix that, or use a completely different approach to models.

It's probably worth looking into how the transition to WASM would affect this. I don't think it would be worth going through a lot of trouble for a solution, that might not work anymore later.

**Comment by IamTheCarl** [comment]
After taking a second look at this I discovered that I critically misunderstood where the panic was being caught.
It's caught in the model's code, not from within Fornjot itself.

With that in mind I moved the location of my call to `fj::abi::initialize_panic_handling();` from within Fornjot to within the model's code.

It works pretty well now. I just need to figure out how to make the `#[fj::macro]`  call automatically insert that.
I am very new to proc macros so that will take a little time.
![image](https://user-images.githubusercontent.com/21977560/227041224-c3e21bc8-9c20-4e40-95dd-bef33bb4c783.png)

**Comment by hannobraun** [comment]
Thank you for your comments, @IamTheCarl!

I think you've convinced me about the serialized format (barring any new insights which might or might not arise). I have some concerns about overhead, but given that the CAD kernel has to do a lot of number-crunching, and WASM's overhead might not be any better, I would assume it doesn't really matter as far as performance goes. Code complexity also shouldn't be too bad, given what we're already dealing with in regards to the FFI boundary (and I'm unclear how much better that would end up being with WASM, if at all).

Some specific comments:


> Multiple execution "backends" will be needed for different platforms. I imagine these backends may eventually translate into other languages even.

I think the current consensus is that Wasmer should work everywhere. (Although there was a lot of discussion about various solutions in that issue.) But that doesn't invalidate your argument. I'm just noting that this item doesn't fit my current understanding.


> One last thing to mention is that this serialized format would be language agnostic. If another language just generated this format, Fornjot would be able to accept it.

:+1: 

A suggestion for the implementation though, I think it might be best to initially stick to something easy and well-understood like [Serde](https://crates.io/crates/serde) (maybe using [Postcard](https://crates.io/crates/postcard) as the serialization format). That would be low-maintenance (compared to anything more advanced or custom), and we can always switch to something else later.


> I do realize this is a bit of a step away from the "code first" approach since this would technically be a file format. Think of it like LLVM's intermediate representation, for CAD models. Someone could even build a more traditional visual editor using this architecture.

Well, this serialized format would be generated on-the-fly by code, and later this would include back-and-forth communication with the kernel. So while this would be a departure from code-first in implementation, it's not really a departure in spirit. It's just a different calling convention, as far as model code is concerned.


> If that all sounds good to you, I'm cool moving this conversation over to #71 and toying with an experimental implementation.

Sounds great!

As I mentioned above, I'm pretty much bought-in at this point, but I'm interested in what the folks over in #71 have to say about this new development.

---

Regarding the issue at hand (the panics), I've seen your pull request and will take a look next.
