### ISSUE TITLE
Validate that coincident `HalfEdge`s refer to same `GlobalEdge`

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#1594]
If two `HalfEdge`s are coincident (which happens where two neighboring faces touch), they need to refer to the same `GlobalEdge`. If they don't, code working with the object graph (like the approximation code) won't know that they are supposed to be the same edge. In the case of the approximation code, this might lead to an invalid triangle mesh being generated. This has been the cause of bugs in the past (https://github.com/hannobraun/Fornjot/issues/494, https://github.com/hannobraun/Fornjot/issues/1162).

To make sure that all instances of this bug have been fixed, and that it stays fixed, we need a validation check for this.

**Comment by A-Walrus** [comment]
How would we check that `HalfEdge`s are coincident? For lines, it seem simple enough, find **start** and **end** values (in 3D) and make sure that they are equal up to some _epsilon_ (possibly with the start and end flipped). However this is **not enough** for more complicated curves, which may meet at the start and end but diverge in the middle.

A simple (but possibly not very elegant) solution would be to **sample** the curves at various points along them and ensure that they are all within our configurable _epsilon_.
This sampling rate could also be part of the `ValidationConfig`. This solution would be very general and work with everything from lines, to circles, to whatever else we have in the future (beziers...)
