### ISSUE TITLE
Incorrect sweep docs?

### ISSUE THREAD

**Issue by A-Walrus** [hannobraun/Fornjot#1799]
https://github.com/hannobraun/Fornjot/blob/a4d75d87245368b4ba964f1698ad898da4f209b6/crates/fj/src/lib.rs#L49-L50

It says that it is swept along the z axis, but from what I can tell it seems that it can be in any vector (length + direction):
https://github.com/hannobraun/Fornjot/blob/a4d75d87245368b4ba964f1698ad898da4f209b6/crates/fj/src/sweep.rs#L23-L24

I'd be happy to fix the docs, unless I'm missing something and it does indeed have to be in the z-axis

**Comment by hannobraun** [comment]
You are right, @A-Walrus, that documentation is outdated! It used to be a sweep along the z-axis (the user only provided the length), but it was changed to an arbitrary a long time ago.
