### ISSUE TITLE
`fj::Sketch` is leaking memory

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#186]
If an `fj::Sketch` is dropped, it will leak the memory of the `Vec` that was provided when constructing it.

I see two solutions for addressing this:
1. Add a `Drop` implementation that frees the memory. Careful though: Currently, `Clone` is derived, which we can get away with, because the raw `Vec` isn't modified, and ownership isn't given away. With a ` Drop` implementation, we also need a custom `Clone` implementation that clones the raw `Vec`. Otherwise, `fj::Sketch` will become unsound.
2. I've recently become aware of [`abi_stable`](https://crates.io/crates/abi_stable). I don't fully understand what it does, but I do know that it contains an [FFI-safe alternative to `Vec`](https://docs.rs/abi_stable/0.10.4/abi_stable/std_types/struct.RVec.html). By using that, we could get rid of the `unsafe` and thus the potential for unsoundness.

I haven't evaluated `abi_stable` yet, but unless there's a reason not to use it, I think it's the preferable option.

Labeling https://github.com/hannobraun/Fornjot/labels/good%20first%20issue, as this is fairly self-contained and can serve as an introduction to the `fj` library.

Thanks to @WeirdConstructor, who reported this [on Matrix](https://matrix.to/#/#fornjot:braun-odw.eu).

**Comment by hannobraun** [comment]
I've recently investigated adding a dependency to `fj`, and that increased compile times substantially (see https://github.com/hannobraun/Fornjot/issues/122#issuecomment-1070977564). Before we decide to go with `abi_stable`, we'd have to make sure that it doesn't have too much of a negative effect.

**Comment by kamirr** [comment]
Is `Sketch` intended to be copied by FFI code? If not, I assume it would be most memory-efficient if we keep a reference counter to the buffer, bump it on `.clone()` and decrement on dropping, then freeing the underlying data only when the counter reaches 0.

If that's fine, I can send you a PR with this change.

**Comment by aunyks** [comment]
What happens when you remove [these lines](https://github.com/hannobraun/Fornjot/blob/main/crates/fj/src/shape_2d.rs#L173-L180) and just return points? I don't understand the need to clone and forget the original.

I haven't tested yet, but I think that `forget()` call is what's causing the leak.

```rust
// Ownership of the pointer in `self.raw_parts` transferred to `points`.
// We work around that, by returning a clone of `points` (hence not
// giving ownership to the caller).
let ret = points.clone();

// Now we just need to forget that `points` ever existed, and we keep
// ownership of the pointer.
mem::forget(points);
```

**Comment by kamirr** [comment]
@aunyks You could then trivially construct two `Vec<_>`s that have the same underlying pointer. This would then lead to reading of deallocated data and double-free scenarios. Please note that `Vec::from_raw_parts(ptr, ..)` does not copy the data behind `ptr`.

The core issue is that `Sketch` owns a heap-allocated chunk of data, but this ownership is smeared across multiple instances due to shallow cloning, which is why it can't simply be deallocated in `Drop`. The `Sketch::to_points` function is completely fine and isn't responsible for the leak.

**Comment by hannobraun** [comment]
@kamirr 
> Is `Sketch` intended to be copied by FFI code? If not, I assume it would be most memory-efficient if we keep a reference counter to the buffer, bump it on `.clone()` and decrement on dropping, then freeing the underlying data only when the counter reaches 0.
> 
> If that's fine, I can send you a PR with this change.

I think your suggestion should work, and I'd be happy to accept a pull request like that. There's only Rust code involved, on both sides of the FFI boundary. The only reason there even *is* an FFI boundary, is because dynamic linking is used to load models, which is only sound with `#[repr(C)]` (due to Rust's lack of a stable ABI).

Please note that I don't expect the memory allocation in `Sketch` to be a bottleneck, so a less efficient solution (like a `Clone` implementation that just creates a new heap allocation) would also be fine. Your solution sounds nicer though.
