### ISSUE TITLE
Consider adding Miri to the CI workflow

### ISSUE THREAD

**Issue by hendrikmaus** [hannobraun/fornjot#213]
[Miri](https://github.com/rust-lang/miri) is a tool to aid spotting undefined behavior in Rust programs. It might be interesting to add this to one's CI pipeline. I have yet to experiment with this myself though.

**Comment by hannobraun** [comment]
Sounds good!

I haven't used Miri either, and we don't do a whole lot of `unsafe` (barely any, I think, aside from `fj::Sketch`), but I think it's a good precaution.

**Comment by hannobraun** [comment]
This issue has been open for a long time, and nothing has been done about it. Adding Miri to the CI build is not a bad idea, but as this point, I see no value in keeping track of it in an open issue. Closing.
