### ISSUE TITLE
Hide platform-specific code behind a single API

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#36]
There is some [platform-specific code in `model.rs`](https://github.com/hannobraun/Fornjot/blob/8a7f7de0b2995ad34994f2b97fd4ce6f9fc27226/src/model.rs#L26-L38). There's also the [watch event handling code in `main.rs`](https://github.com/hannobraun/Fornjot/blob/8a7f7de0b2995ad34994f2b97fd4ce6f9fc27226/src/main.rs#L133-L140). This is fine for now, but following this approach everywhere will get unwieldy.

I think the following concept would be better:
- Create a new module, `platforms`, that contains a `Platform` trait.
- This trait should define a minimal interface, such that all platform-specific code lives in implementations of that trait.
- Otherwise those trait implementations should contain as little code as possible, to prevent duplication.
- Avoid the use of `#[cfg(...)]` as much as practical. All code should be compiled on all platforms, to prevent errors from creeping in.
- Use of `cfg!(...)` is fine, of course.

**Comment by hannobraun** [comment]
Marking this one as `good first issues`, as it concerns a limited amount of code (which I linked in the original issue description) and doesn't require lots of knowledge about Fornjot.

**Comment by ozghimire** [comment]
Is anyone working on this? I would like to work on this, also has the requirements changed from last it was updated?

**Comment by hannobraun** [comment]
Hey @ozghimire, thank you for the interest!

As far as I know, nobody is working on this. Feel free to pick it up!

The requirements here are still up-to-date. I think the platform-specific code has changed very little, since I created this issue.

**Comment by ozghimire** [comment]
Awesome, can you assign me this and I will start working on it.

**Comment by hannobraun** [comment]
You can just start working whenever you want, and don't need me to officially assign you. But since you asked, I'll happily do it :grin:

**Comment by hannobraun** [comment]
Hey @ozghimire, two notes:
1. I've extracted the former `model` module into a separate crate in #381, `fj-host`. The only piece of platform-independent code now lives there: https://github.com/hannobraun/Fornjot/blob/ff5564614bf6bfdd945db95daba122ee64bbdd7b/fj-host/src/lib.rs#L36-L44
2. The issue description mentions the watch event handling code. This also lives in `fj-host` now, but I'm actually no longer sure what specifically I was referring to when I mentioned that. I assume that I was thinking that it might make sense to listen for different event on different platforms, but it's not clear that is the case.
#29 is an issue that might require listening to different events on different platforms to be resolved, but it's actually not clear whether that is the case, and what's causing the issue in the first place.
In any case, I think you can ignore the event handling code for the purposes of this issue.

**Comment by ozghimire** [comment]
@hannobraun So as part of the change, so the platform module should live inside the fj-host crate or it should be inside the fj-app?

**Comment by hannobraun** [comment]
@ozghimire 
> So as part of the change, so the platform module should live inside the fj-host crate or it should be inside the fj-app?

It needs to be in `fj-host`, as that's where it's needed.
