### ISSUE TITLE
Fix comment type of tolerance command line parameter

### ISSUE THREAD

**Issue by mxdamien** [hannobraun/Fornjot#360]
Hi !

When adding a command line parameter for model deviation tolerance in #118 with 8c3e42f7260827890e12956d2094c7606e01e836 I used a regular comment instead of a documentation comment. Sorry for that. 

see #359

**Comment by hannobraun** [comment]
Hey @mxdamien, thanks for opening this issue!

No need to apologize! I make mistakes like that all the time. And also, I missed this in review, so who's fault is it really? :grin:
