### ISSUE TITLE
Set up CI build

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#41]
Set up a CI build, probably using GitHub Actions, that runs on all pushes to `main` and all pull requests.

**Comment by mxdamien** [comment]
See #45 

On Windows `kernel::geometry::surfaces::tests::test_transform` fails. Possibly due to some floating point precision problem.  However, generally the CI builds are working.

**Comment by hannobraun** [comment]
Yes, I agree that it's a floating point precision problem (or rather, the epsilon value used to compare floating point values in the test doesn't seem to be large enough on all platforms, for some reason). I've opened #47 to track this problem.

Thanks again, @mxdamien!
