### ISSUE TITLE
Broken documentation in fj-kernel.

### ISSUE THREAD

**Issue by freylint** [hannobraun/Fornjot#490]
After adding the missing documentation in `fj-viewer` the output of cargo clippy -- -D missing_docs produces several warnings related to potentially broken documentation in `fj-kernel`.

<details>
<summary>Output of `cargo clippy -- -D missing_docs on working branch of #487</summary>
warning: unresolved link to `Shape`
   --> crates/fj-kernel/src/shape/stores.rs:162:43
    |
162 | /// A handle to an object stored within [`Shape`]
    |                                           ^^^^^ no item named `Shape` in scope
    |
    = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Shape`
   --> crates/fj-kernel/src/shape/stores.rs:222:42
    |
222 | /// Returned by various methods of the [`Shape`] API.
    |                                          ^^^^^ no item named `Shape` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Shape`
   --> crates/fj-kernel/src/shape/validate.rs:170:53
    |
170 | /// Returned by the various `add_` methods of the [`Shape`] API
    |                                                     ^^^^^ no item named `Shape` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Handle`
  --> crates/fj-kernel/src/topology/mod.rs:12:59
   |
12 | //! geometry are considered equal, even if they contain [`Handle`]s that refer
   |                                                           ^^^^^^ no item named `Handle` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Shape`
  --> crates/fj-kernel/src/topology/mod.rs:13:31
   |
13 | //! to objects in different [`Shape`] instances.
   |                               ^^^^^ no item named `Shape` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Handle`
  --> crates/fj-kernel/src/topology/mod.rs:15:46
   |
15 | //! This is different from the equality of [`Handle`], which follows a strict
   |                                              ^^^^^^ no item named `Handle` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Handle`
  --> crates/fj-kernel/src/topology/mod.rs:16:35
   |
16 | //! definition of identity. Two [`Handle`]s are only considered equal, if they
   |                                   ^^^^^^ no item named `Handle` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `self::kernel::topology`
  --> crates/fj-kernel/src/topology/edges.rs:18:23
   |
18 | /// Please refer to [`crate::kernel::topology`] for documentation on the
   |                       ^^^^^^^^^^^^^^^^^^^^^^^ no item named `kernel` in module `fj_kernel`

warning: public documentation for `builder` links to private item `CycleBuilder`
  --> crates/fj-kernel/src/topology/edges.rs:32:35
   |
32 |     /// Build a cycle using the [`CycleBuilder`] API
   |                                   ^^^^^^^^^^^^ this item is private
   |
   = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default
   = note: this link will resolve properly if you pass `--document-private-items`

warning: unresolved link to `self::kernel::topology`
  --> crates/fj-kernel/src/topology/edges.rs:64:23
   |
64 | /// Please refer to [`crate::kernel::topology`] for documentation on the
   |                       ^^^^^^^^^^^^^^^^^^^^^^^ no item named `kernel` in module `fj_kernel`

warning: unresolved link to `self::kernel::topology`
  --> crates/fj-kernel/src/topology/faces.rs:17:23
   |
17 | /// Please refer to [`crate::kernel::topology`] for documentation on the
   |                       ^^^^^^^^^^^^^^^^^^^^^^^ no item named `kernel` in module `fj_kernel`

warning: public documentation for `builder` links to private item `FaceBuilder`
  --> crates/fj-kernel/src/topology/faces.rs:69:34
   |
69 |     /// Build a face using the [`FaceBuilder`] API
   |                                  ^^^^^^^^^^^ this item is private
   |
   = note: this link will resolve properly if you pass `--document-private-items`

warning: unresolved link to `self::kernel::topology`
  --> crates/fj-kernel/src/topology/vertices.rs:20:23
   |
20 | /// Please refer to [`crate::kernel::topology`] for documentation on the
   |                       ^^^^^^^^^^^^^^^^^^^^^^^ no item named `kernel` in module `fj_kernel`

warning: unresolved link to `Shape::with_minimum_distance`
  --> crates/fj-kernel/src/topology/vertices.rs:32:7
   |
32 | /// [`Shape::with_minimum_distance`].
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the struct `Shape` has no field or associated item named `with_minimum_distance`

warning: `fj-kernel` (lib doc) generated 14 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
</details>

[commit hash](https://github.com/hannobraun/Fornjot/pull/487/commits/74b3d7e64751ef0085a53d137a35fc98d2a7664d)

This reveals that it may be a good idea to test the generation of documentation in CI as well.

**Comment by hannobraun** [comment]
Thank you for opening this issue, @freylint!

There's already an open issue that tracks checking these kinds of problem (#271). I'm going to close this one, and add a note there.
