### ISSUE TITLE
Release automation can fail, because just-published crate is not found

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#788]
Check out this run of the CD pipeline: https://github.com/hannobraun/Fornjot/runs/7235683927?check_suite_focus=true

`fj` is being published successfully, but right after, `fj-host` fails, because it can't find `fj`. I suspect this is due to caching on crates.io.

I'm not sure what the best way to fix this is, but here are some ideas:

- Wait for a short delay after publishing a crate.
- After publishing a crate, query crates.io until it is available.
- Retry after a short delay, if publishing a crate fails.
- Retry if `cargo publish` fails for this specific reason

**Comment by hannobraun** [comment]
Here's the same thing happening again: https://github.com/hannobraun/Fornjot/runs/7235972641?check_suite_focus=true

This seems to be a common occurrence, which makes this issue a high priority.

**Comment by hannobraun** [comment]
And another one: https://github.com/hannobraun/Fornjot/runs/7236214289?check_suite_focus=true

This absolutely needs to be fixed before the next release.

**Comment by hendrikmaus** [comment]
I would propose to go with the option "After publishing a crate, query crates.io until it is available."

I think it is the cleanest approach. 

I will open a pull request with a fix.

**Comment by hendrikmaus** [comment]
FYI: it is a known issue https://github.com/rust-lang/cargo/issues/9507

**Comment by hannobraun** [comment]
> I would propose to go with the option "After publishing a crate, query crates.io until it is available."
> 
> I think it is the cleanest approach.

I agree.


> I will open a pull request with a fix.

Thank you!

---

By the way, I know I said this absolutely needs to be fixed before the next release, but... I changed my mind :smile: 

This issue is very annoying, but it is not critical. It just makes the release take more time. #538 on the other hand is critical, as it could cause problems to be missed completely. So fixing #538 is actually more important, and we might want to keep this issue around as a ready source of errors to test fixes to #538 with.

**Comment by hannobraun** [comment]
This issue has not been fixed, unfortunately!

![image](https://user-images.githubusercontent.com/85732/179511775-51ee1dbc-c90d-41b5-a156-7f16146d50c2.png)

From here: https://github.com/hannobraun/Fornjot/runs/7389324150?check_suite_focus=true

Seems like the behavior of crates.io is less rational than we expected. I think that makes "retry publish until it works" the best option.
