### ISSUE TITLE
Try to speed up CI build

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/Fornjot#82]
The CI build is slow, mostly because the Windows build takes pretty long. While this is not a critical issue, it would be great if the build was a lot faster.

It should be possible to cache the Cargo output, so all dependencies don't have to be rebuilt all the time. I haven't done that before with GitHub Actions, but there are probably existing solutions, and it should make the build much faster.

**Comment by mxdamien** [comment]
Hey !

Caching looks good in my test. Obviously this only starts working with the second run of the CI builds.

![image](https://user-images.githubusercontent.com/17779789/151788925-eb641bef-8b27-43a4-9812-be5a13610b21.png)

**Comment by hannobraun** [comment]
Nice! Love those numbers!
