### ISSUE TITLE
Shape types should implement equality

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hannobraun/Fornjot#831]
As currently implemented, none of the geometric types in the `fj` crate implement `PartialEq`. Is there a specific reason for this, or was it done just as a forward-compatiblity measure? For example, because we might want to add trait/function-based geometry in the future which doesn't have a definition for value equality.

If possible, it'd be nice to `#[derive(PartialEq)]` because then model implementations can write unit tests to check they generate the correct shape.

As an example for when this could be useful, see the following [smoke test](https://github.com/Michael-F-Bryan/fornjot-plugins/blob/cd6b82e7a806965d12cf0fd1f1682eebb3055d3f/models/cuboid/tests/integration.rs#L5-L30) for my `cuboid` model.

```rust
#[test]
fn load_cuboid_and_generate_geometry() {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let target_dir = crate_dir.parent().unwrap().parent().unwrap().join("target");

    let model = Model::from_path(crate_dir.into(), Some(target_dir.into())).unwrap();

    let mut arguments = HashMap::new();
    arguments.insert("x".to_string(), "10".to_string());
    let actual = model.load_once(&Parameters(arguments)).unwrap();

    let rectangle = fj::Sketch::from_points(vec![
        [-5.0, -1.0],
        [10.0 / 2., -2.0 / 2.],
        [10.0 / 2., 2.0 / 2.],
        [-10.0 / 2., 2.0 / 2.],
    ])
    .with_color([100, 255, 0, 200]);
    let expected = fj::Sweep::from_path(rectangle.into(), [0., 0., 3.0]);

    // TODO: Enable this assertion when we can compare shapes for equality.
    // https://github.com/hannobraun/Fornjot/issues/831

    // assert_eq!(actual, expected);
    let _ = (actual, expected);
}
```

**Comment by hannobraun** [comment]
There's no deep reason for why they don't derive `PartialEq`, nor is there any specific reason why they derive the types they do derive, beyond "it was needed at some point". Any changes here that help you (or anyone else) are definitely welcome!

Forward compatibility is not a concern at this point. We are far away from even approach a mature design. This stuff will change a million times before it settles down, I'm sure.
